[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  [context.production.environment]
    API_URL = "https://next-dorm-be.fly.dev"
[build]
  publish = "build/"
  command = "FE_URL=$DEPLOY_URL npm run build"
